//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminAccount()
        {
            this.AdminLogs = new HashSet<AdminLog>();
            this.Interfaces = new HashSet<Interface>();
            this.News = new HashSet<News>();
        }
    
        public string C_Username { get; set; }
        public string C_Password { get; set; }
        public string C_Name { get; set; }
        public string C_Sex { get; set; }
        public string C_Avatar { get; set; }
        public string C_Address { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public string C_Role { get; set; }
        public Nullable<System.DateTime> C_Lastlogin { get; set; }
        public Nullable<System.DateTime> C_LastChangePassword { get; set; }
        public string C_Logs { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminLog> AdminLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interface> Interfaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
    }
}
