//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public string C_ID { get; set; }
        public string C_Customer { get; set; }
        public Nullable<int> C_ProdCount { get; set; }
        public Nullable<int> C_OrderValue { get; set; }
        public string C_ReceiverName { get; set; }
        public string C_ReceiverSex { get; set; }
        public string C_ReceiverAddress { get; set; }
        public string C_ReceiverPhone { get; set; }
        public string C_ReceiverEmail { get; set; }
        public string C_DeliveryBy { get; set; }
        public string C_PaymentMethod { get; set; }
        public Nullable<int> C_Status { get; set; }
        public string C_Note { get; set; }
        public string C_Logs { get; set; }
        public string C_ReceiverDistrict { get; set; }
        public string C_ReceiverProvince { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
