//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMarketing
    {
        public string C_Email { get; set; }
        public string C_Name { get; set; }
        public string C_Sex { get; set; }
        public string C_Phone { get; set; }
        public string C_Address { get; set; }
        public string C_IPClient { get; set; }
        public Nullable<int> C_Status { get; set; }
        public string C_Logs { get; set; }
    }
}
