//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsCategory()
        {
            this.News = new HashSet<News>();
            this.NewsCategory1 = new HashSet<NewsCategory>();
        }
    
        public string C_ID { get; set; }
        public string C_IDParent { get; set; }
        public string C_Title { get; set; }
        public string C_SlugTitle { get; set; }
        public string C_ImagePath { get; set; }
        public string C_Description { get; set; }
        public Nullable<int> C_Priority { get; set; }
        public string C_Logs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsCategory> NewsCategory1 { get; set; }
        public virtual NewsCategory NewsCategory2 { get; set; }
    }
}
