//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string C_ID { get; set; }
        public string C_Category { get; set; }
        public string C_Title { get; set; }
        public string C_Slugtitle { get; set; }
        public string C_ImagePath { get; set; }
        public string C_Description { get; set; }
        public string C_Content { get; set; }
        public string C_Hashtag { get; set; }
        public Nullable<int> C_Views { get; set; }
        public Nullable<int> C_Status { get; set; }
        public Nullable<System.DateTime> C_CreateAt { get; set; }
        public Nullable<System.DateTime> C_ModifyAt { get; set; }
        public string C_PostedBy { get; set; }
        public string C_Logs { get; set; }
    
        public virtual AdminAccount AdminAccount { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
