//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public string C_ID { get; set; }
        public string C_Cate { get; set; }
        public string C_Title { get; set; }
        public string C_SlugTitle { get; set; }
        public string C_ImagePath { get; set; }
        public string C_ImagePath_2 { get; set; }
        public string C_ImagePath_3 { get; set; }
        public string C_ImagePath_4 { get; set; }
        public string C_Decription { get; set; }
        public string C_Content { get; set; }
        public Nullable<int> C_Price { get; set; }
        public string C_Unit { get; set; }
        public string C_CreateBy { get; set; }
        public Nullable<int> C_Total { get; set; }
        public Nullable<int> C_Inventory { get; set; }
        public Nullable<System.DateTime> C_CreateAt { get; set; }
        public Nullable<System.DateTime> C_ModifyAt { get; set; }
        public string C_Logs { get; set; }
        public string C_Views { get; set; }
        public Nullable<int> C_IsApproved { get; set; }
        public Nullable<int> C_IsShow { get; set; }
        public Nullable<int> C_IsDeleted { get; set; }
        public string C_Productdetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
