//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
            this.ChildProductCategories = new HashSet<ProductCategory>();
        }
    
        public string C_ID { get; set; }
        public string C_IDParent { get; set; }
        public string C_Title { get; set; }
        public string C_SlugTitle { get; set; }
        public string C_ImagePath { get; set; }
        public string C_IconPath { get; set; }
        public string C_Banner { get; set; }
        public string C_Decription { get; set; }
        public Nullable<int> C_Priority { get; set; }
        public string C_Logs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ChildProductCategories { get; set; }
        public virtual ProductCategory ParentProductCategory { get; set; }
    }
}
