//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int C_ID { get; set; }
        public Nullable<int> C_SalesPromotionID { get; set; }
        public string C_Product { get; set; }
        public string C_Logs { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesPromotion SalesPromotion { get; set; }
    }
}
