//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.AdminAccounts = new HashSet<AdminAccount>();
        }
    
        public string C_ID { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> C_Add_Category { get; set; }
        public Nullable<int> C_Update_Category { get; set; }
        public Nullable<int> C_Delete_Category { get; set; }
        public Nullable<int> C_Approve_Product { get; set; }
        public Nullable<int> C_Update_Product { get; set; }
        public Nullable<int> C_Delete_Product { get; set; }
        public Nullable<int> C_Add_News { get; set; }
        public Nullable<int> C_Update_News { get; set; }
        public Nullable<int> C_Delete_News { get; set; }
        public Nullable<int> C_Add_Role { get; set; }
        public Nullable<int> C_Update_Role { get; set; }
        public Nullable<int> C_Delete_Role { get; set; }
        public string C_Logs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminAccount> AdminAccounts { get; set; }
    }
}
