//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPromotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesPromotion()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int C_ID { get; set; }
        public string C_Title { get; set; }
        public string C_Decription { get; set; }
        public string C_Range { get; set; }
        public Nullable<int> C_Discount { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<System.DateTime> C_To { get; set; }
        public Nullable<int> C_Status { get; set; }
        public string C_CreateBy { get; set; }
        public Nullable<System.DateTime> C_CreateAt { get; set; }
        public string C_Logs { get; set; }
    
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
