//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string C_ID { get; set; }
        public string C_Title { get; set; }
        public string C_SlugTitle { get; set; }
        public string C_Decription { get; set; }
        public string C_Avatar { get; set; }
        public string C_Address { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public Nullable<System.DateTime> C_CreateAt { get; set; }
        public string C_Owner { get; set; }
        public string C_Logs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
