//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZABDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.Bookings = new HashSet<Booking>();
            this.Shops = new HashSet<Shop>();
        }
    
        public string C_Username { get; set; }
        public string C_Password { get; set; }
        public string C_Name { get; set; }
        public string C_Sex { get; set; }
        public string C_Avatar { get; set; }
        public string C_Address { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public Nullable<System.DateTime> C_Lastlogin { get; set; }
        public Nullable<System.DateTime> C_LastChangePassword { get; set; }
        public Nullable<int> C_IsKYC { get; set; }
        public string C_Logs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
